//------------------------------------------------------------------------------
// <auto-generated>
//     This code is created by the program.
//     Executable version: 4.0.30319.42000
//
//     Changes to this file may cause malfunction and will be lost if the code is re-generated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyLayerApp.Resources.Strings {
    using System;


    /// <summary>
    /// A resource class with strict typing to find localized strings, etc.
    /// </ summary>
    // This class is created automatically by the StronglyTypedResourceBuilder class
    // using a tool such as ResGen or Visual Studio.
    // To add or remove a member, change the .ResX file and run ResGen again
    // with the / str parameter or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached instance of the ResourceManager used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyLayerApp.Resources.Strings.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overwrites the CurrentUICulture property of the current thread for all
        /// calls to the resource using this resource class with strict typing.
        /// </ summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks for a localized string, similar toCurrent Data.
        /// </summary>
        public static string CurrentData {
            get {
                return ResourceManager.GetString("CurrentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks for a localized string, similar toExchange Data.
        /// </summary>
        public static string ExchangeData {
            get {
                return ResourceManager.GetString("ExchangeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks for a localized string, similar toHistorical Data.
        /// </summary>
        public static string HistoricalData {
            get {
                return ResourceManager.GetString("HistoricalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks for a localized string, similar toSettings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
